export const PG_VERIFICATION_STATUSES = {
  INCOMPLETE: "incomplete",
  PENDING_REVIEW: "pending_review",
  APPROVED: "approved",
  REJECTED: "rejected",
};

export const PG_SERVICE_TYPE_VALUES = [
  "full-stack-pg",
  "upi-only-pg",
  "pos",
  "cross-border",
  "one-click",
  "risk-frm",
  "orchestration",
];

/** Flat keys stored under PaymentProvider.onboarding */
export const PG_ONBOARDING_KEYS = [
  "serviceType",
  "legalEntityName",
  "brandName",
  "companyLogo",
  "websiteUrl",
  "headquartersCountry",
  "headquartersCity",
  "yearEstablished",
  "merchantBaseCount",
  "countriesSupported",
  "rbiPapgStatus",
  "pciDssStatus",
  "companyOverview",
  "upiMdr",
  "creditCardMdr",
  "debitCardMdr",
  "internationalMdr",
  "walletCharges",
  "netBankingCharges",
  "emiBnplCharges",
  "refundFee",
  "chargebackFee",
  "amcPlatformFees",
  "setupFees",
  "instantSettlementCharges",
  "offersPromotions",
  "hardwareCost",
  "annualMaintenanceContract",
  "monthlyRental",
  "forexMarkup",
  "settlementCurrency",
  "settlementInfrastructure",
  "multiCurrencyWallet",
  "perTransactionFee",
  "monthlyRetainer",
  "onboardingChecklist",
  "onboardingTat",
  "settlementCycle",
  "refundSla",
  "approvalComplexity",
  "dedicatedAccountManager",
  "merchantSupportAvailability",
  "escalationSupport",
  "instantSettlementAvailability",
  "internationalPaymentsSupport",
  "offlineModeSupport",
  "gstBillingSupport",
  "averageResponseTime",
  "restrictedCategories",
  "bestSuitedBusinessTypes",
  "smartTags",
  "suggestNewTag",
  "sortByCategories",
  "features",
  "suggestNewFeature",
  "apiDocumentationUrl",
  "sdkAvailability",
  "pluginAvailability",
  "sandboxAccess",
  "webhookSupport",
  "mobileSdkSupport",
  "merchantSuccessStoriesUrl",
  "caseStudiesUrl",
  "talkToExpertEnabled",
  "expertName",
  "expertDesignation",
  "expertEmail",
  "expertMobile",
  "expertDescription",
  "calendlyUrl",
  "calendarSynced",
  "availabilitySlots",
  "experts",
];
